# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9bb422da18ccf0fd7480cc96ce4939e9e661b7b738f920da48d17b8dad141f3f5d10ff8a67f24c988d73b0745be8aff9042cf1413c37057ca7a219517d32933

test:
  secret_key_base: 9459a1ca0ebf4cfc5e5c1a88d43ac244fdaaab1bccb8872bbca5f797c708f64bfa5c3314612cc48bc9d036f3f58eaaf8d809f9bbb6b7d48962c03ec2f9c2d091

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
